version: '3'

services:
    nginx: # Handles routing; Routes traffic to the appropriate service
        restart: 'always' # Critical service, always needs to restart
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '8080:80'
    postgres:
        image: 'postgres:11.5-alpine'
        container_name: 'database'
        env_file:
            - 'server/server.env'
        volumes:
            - 'pg_data:/var/lib/postgresql/data'
        ports: 
            - '5432:5432'

    redis:
        image: 'redis:3.0-alpine'
        command: redis-server --requirepass devpassword
        volumes:
            - 'redis:/var/lib/redis/data'
        ports:
            - '6379:6379'


    celery:
        build:
            context: ./server
            dockerfile: Dockerfile.dev 
        command: celery worker -l info -A app.blueprints.contact.tasks
        env_file:
            - server/server.env
        volumes:
            - .:/server/app


    api: # server
        restart: 'on-failure'
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - ./server:/app
        command: >
            gunicorn -b 0.0.0.0:8000
            --access-logfile -
            --reload
            "app.app:create_app()"
        env_file: # Pull server environment variables from an .env file
            - server/server.env

        depends_on:
            - postgres


    client: # Treat the UI as a separate service.
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app

volumes:
    redis:
    pg_data:
